// enum
package enums

type ENCRYPT_ENUM int

const (
	_ ENCRYPT_ENUM = 0x1F + iota
	ENCRYPT_NONE
	ENCRYPT_AES_128_CTR
	ENCRYPT_AES_192_CTR
	ENCRYPT_AES_256_CTR
	ENCRYPT_AES_128_CFB
	ENCRYPT_AES_192_CFB
	ENCRYPT_AES_256_CFB
	ENCRYPT_RC4
	ENCRYPT_RC4_MD5
	ENCRYPT_RC4_MD5_6
	ENCRYPT_SALSA20
	ENCRYPT_CHACHA20
	ENCRYPT_CHACHA20_IETF
)

type PROTOCOL_ENUM int

const (
	_ PROTOCOL_ENUM = 0x2F + iota
	PROTOCOL_ORIGIN
	PROTOCOL_VERIFY_DEFLATE
	PROTOCOL_AUTH_AES128_MD5
	PROTOCOL_AUTH_AES128_SHA1
	PROTOCOL_AUTH_CHAIN_A
	PROTOCOL_AUTH_CHAIN_B
)

type OBFS_ENUM int

const (
	_ OBFS_ENUM = 0x3F + iota
	OBFS_PLAIN
	OBFS_HTTP_SIMPLE
	OBFS_HTTP_POST
	OBFS_RANDOM_HEAD
	OBFS_TLS1_2_TICKET_AUTH
	OBFS_TLS1_2_TICKET_FASTAUTH
)

var ENUM_ENCRYPT_MAP = make(map[ENCRYPT_ENUM]string)
var ENUM_PROTOCOL_MAP = make(map[PROTOCOL_ENUM]string)
var ENUM_OBFS_MAP = make(map[OBFS_ENUM]string)

func init() {
	//加密方式
	ENUM_ENCRYPT_MAP[ENCRYPT_NONE] = "none"
	ENUM_ENCRYPT_MAP[ENCRYPT_AES_128_CTR] = "aes-128-ctr"
	ENUM_ENCRYPT_MAP[ENCRYPT_AES_192_CTR] = "aes-192-ctr"
	ENUM_ENCRYPT_MAP[ENCRYPT_AES_256_CTR] = "aes-256-ctr"
	ENUM_ENCRYPT_MAP[ENCRYPT_AES_128_CFB] = "aes-128-cfb"
	ENUM_ENCRYPT_MAP[ENCRYPT_AES_192_CFB] = "aes-192-cfb"
	ENUM_ENCRYPT_MAP[ENCRYPT_AES_256_CFB] = "aes-256-cfb"
	ENUM_ENCRYPT_MAP[ENCRYPT_RC4] = "rc4"
	ENUM_ENCRYPT_MAP[ENCRYPT_RC4_MD5] = "rc4-md5"
	ENUM_ENCRYPT_MAP[ENCRYPT_RC4_MD5_6] = "rc4-md5-6"
	ENUM_ENCRYPT_MAP[ENCRYPT_SALSA20] = "salsa20"
	ENUM_ENCRYPT_MAP[ENCRYPT_CHACHA20] = "chacha20"
	ENUM_ENCRYPT_MAP[ENCRYPT_CHACHA20_IETF] = "chacha20-ietf"
	//协议
	ENUM_PROTOCOL_MAP[PROTOCOL_ORIGIN] = "origin"
	ENUM_PROTOCOL_MAP[PROTOCOL_VERIFY_DEFLATE] = "verify_deflate"
	ENUM_PROTOCOL_MAP[PROTOCOL_AUTH_AES128_MD5] = "auth_aes128_md5"
	ENUM_PROTOCOL_MAP[PROTOCOL_AUTH_AES128_SHA1] = "auth_aes128_sha1"
	ENUM_PROTOCOL_MAP[PROTOCOL_AUTH_CHAIN_A] = "auth_chain_a"
	ENUM_PROTOCOL_MAP[PROTOCOL_AUTH_CHAIN_B] = "auth_chain_b"
	//混淆方式
	ENUM_OBFS_MAP[OBFS_PLAIN] = "plain"
	ENUM_OBFS_MAP[OBFS_HTTP_SIMPLE] = "http_simple"
	ENUM_OBFS_MAP[OBFS_HTTP_POST] = "http_post"
	ENUM_OBFS_MAP[OBFS_RANDOM_HEAD] = "random_head"
	ENUM_OBFS_MAP[OBFS_TLS1_2_TICKET_AUTH] = "tls1.2_ticket_auth"
	ENUM_OBFS_MAP[OBFS_TLS1_2_TICKET_FASTAUTH] = "tls1.2_ticket_fastauth"

}
